"""Arrumando os models criando todas as classes previamente planejadas

Revision ID: c7f6325dbf30
Revises: 40ecfe6cd362
Create Date: 2024-03-27 10:53:55.747927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c7f6325dbf30'
down_revision: Union[str, None] = '40ecfe6cd362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemprodutos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemprodutos',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('produto_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('preco', sa.FLOAT(), nullable=False),
    sa.Column('cor', sa.VARCHAR(length=50), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=True),
    sa.Column('imagens', sqlite.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DATETIME(), nullable=False),
    sa.Column('data_atualizacao', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
